services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=commitchange_development_legacy
      - shm_size: 1g
  web:
    build:
      context: .
      args:
        BASE_RELEASE: ${BASE_RELEASE:-bookworm}
    volumes:
      - ${HOME}${USERPROFILE}/.netrc:/home/app/.netrc # for heroku credentials
      - ./vendor/bundle:/usr/local/bundle
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db:/app/db
      - ./javascripts:/app/javascripts
      - ./lib:/app/lib
      - ./script:/app/script
      - ./types:/app/types
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    environment:
      - DATABASE_HOST=db
      - BUILD_DATABASE_URL=postgres://admin:password@db/commitchange_development_legacy
    depends_on:
      - db
    env_file: ".env"
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp/pids/
  worker:
    build:
      context: .
      args:
        BASE_RELEASE: ${BASE_RELEASE:-bookworm}
    volumes:
      - ${HOME}${USERPROFILE}/.netrc:/home/app/.netrc
      - ./vendor/bundle:/usr/local/bundle
      - ./app:/app/app
      - ./bin:/app/bin
      - ./config:/app/config
      - ./db:/app/db
      - ./javascripts:/app/javascripts
      - ./lib:/app/lib
      - ./script:/app/script
      - ./types:/app/types
    environment:
      - DATABASE_HOST=db
      - BUILD_DATABASE_URL=postgres://admin:password@db/commitchange_development_legacy
    depends_on:
      - db
      - web
    env_file: ".env"
    command: ["bin/rails", "jobs:work"]
    tty: true
    stdin_open: true
volumes:
  db_data:
