mailer:
  host: "https://commitchange-test.herokuapp.com"
  delivery_method: "smtp"
  smtp_settings:
    address: "sandbox.smtp.mailtrap.io"
    port: 2525
    user_name: <%= ENV['MAILTRAP_USERNAME'] %>
    password: <%= ENV['MAILTRAP_PASSWORD'] %>
    authentication:  "plain"
    enable_starttls: true

cdn:
  url: "https://d1kiu7z4pkqkyu.cloudfront.net"

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: us-west-1
  bucket: commitchange

button_config:
  url: "https://commitchange-test.herokuapp.com"

image:
  host: "https://dmnsmycmdpaix.cloudfront.net"

api_domain:
  url: "https://commitchange-test.herokuapp.com"