# License: CC0-1.0
# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  database: houdini_development
  pool: 20
  username: houdini_user
  password: password
  host: <%= ENV['DATABASE_HOST']  || 'localhost' %>

test:
  adapter: postgresql
  encoding: unicode
  database: houdini_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: houdini_user
  password: password
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
ci:
  adapter: postgresql
  encoding: unicode
  database: houdini_ci
  pool: 5
  username: houdini_user
  password: password
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>



  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
production:
  adapter: postgresql
  encoding: unicode
  database: houdini_production
  pool: 5
  username: admin
  password: password

staging:
  adapter: postgresql
  encoding: unicode
  database: houdini_staging
  pool: 5
  username: admin
  password: password
