# License: CC0-1.0

source_tokens:
  max_uses: 1
  expiration_time: 1200
  event_donation_source:
    time_after_event: 1728000
    max_uses: 20

intntl:
  currencies: ["usd"]
  all_currencies:
    - unit: "dollars"
      subunit: "cents"
      symbol: "$"
      abbv: "usd"
      format: "%u%n"
    - unit: "euro"
      subunit: "cents"
      symbol: "€"
      abbv: "eur"
      format: "%n%u"

general:
  name: 'CommitChange'

devise:
  mailer_sender: "support@commitchange.com"

mailer:
  default_from: "CommitChange Team <support@commitchange.com>"
  email: "support@commitchange.com"

default_bp:
  id: 40

intntl:
  currencies: ["usd"]
  all_currencies:
   - unit: "dollars"
     subunit: "cents"
     symbol: "$"
     abbv: "usd"
     format: "%u%n"
   - unit: "euro"
     subunit: "cents"
     symbol: "€"
     abbv: "eur"
     format: "%n%u"


language: "en"
available_locales: ["en"]
show_state_field: true

payment_provider:
  stripe_connect: true
  stripe_proprietary_v2_js: false


page_editor:
  editor: 'quill'



