name: "Pull Request Labeler"
on:
  - pull_request

permissions: write-all

jobs:
  label:
    runs-on: ubuntu-latest
    steps:

      - uses: srvaroa/labeler@v0.8
        with:
          config_path: .github/labeler_config.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"