# License: LGPL-3.0-or-later
name: NOTICE-ruby update
on:
  workflow_run:
    workflows: ["NOTICE-ruby verification"]
    types: 
      - completed
env:
  os: ubuntu-20.04
  ruby: '2.7.4'
jobs:
  notice_ruby:
    runs-on: ubuntu-20.04
    steps:
      - name: download branch
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/download-artifact@v2
        with:
          name: branch_to_update

      - name: Read package.json
        id: branch
        uses: juliangruber/read-file-action@v1
        with:
          path: ./branch.txt
      - uses: actions/checkout@v2
        with: 
          ref: ${{ steps.branch.outputs.content }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - name: Update NOTICE-ruby on Dependabot
        if: ${{ github.event.workflow_run.conclusion == 'failure'  && github.actor == 'dependabot[bot]' }}
        run: |
          echo ${{ github.event.workflow_run }}
         
