# License: LGPL-3.0-or-later
name: NOTICE-ruby verification
on: 
  push:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
  pull_request:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
env:
  os: ubuntu-20.04
  ruby: '2.7.4'
jobs:
  notice_ruby:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
      - uses: actions/cache@v2
        name: Use Gem cache
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ env.os }}-${{ env.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ env.os }}-${{ env.ruby }}-
      - run: |
          bundle config deployment true
          bundle config path vendor/bundle
          bundle install --jobs 4
      - name: run notice:ruby:verify
        run: |
            bin/rails notice:ruby:verify
      - name: Describe what's in context
        run: |
          echo ${{ failure() }}
          echo ${{ github.actor }}
          echo ${{ github.event_name }}
      - name: Update NOTICE-ruby on Dependabot
        if: ${{ failure() && github.actor == 'apps/dependabot' && github.event_name == 'push'}}
        run: |
          bin/rails notice:ruby:update
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update NOTICE-ruby"
          git push HEAD:${{ github.ref }}
