# License: LGPL-3.0-or-later
name: NOTICE-ruby verification
on: 
  push:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
  pull_request:
    paths:
      - Gemfile
      - Gemfile.lock
      - NOTICE-ruby
    types: [opened, reopened, synchronize]
env:
  os: ubuntu-20.04
  ruby: '2.7.6'
jobs:
  notice_ruby:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby }}
          bundler-cache: true
      - name: run notice:ruby:verify
        run: |
            bin/rails notice:ruby:verify
